# Generated by Django 3.0.6 on 2020-05-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdpapp', '0002_auto_20200524_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
