# Generated by Django 3.0.6 on 2020-05-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdpapp', '0005_auto_20200524_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
