# Generated by Django 3.0.6 on 2020-05-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdpapp', '0006_delete_movement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_note',
            new_name='client_notes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_note',
            new_name='product_notes',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_products',
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_quantity', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Quantidade')),
                ('movement_purchase_price', models.DecimalField(decimal_places=3, help_text="Introduza '0' para ignorar.", max_digits=7, null=True, verbose_name='Preço de Custo')),
                ('movement_selling_price', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Preço de Venda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mdpapp.Product', verbose_name='Produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mdpapp.Sale', verbose_name='Venda')),
            ],
        ),
    ]
