# Generated by Django 3.0.6 on 2020-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdpapp', '0007_auto_20200524_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_notes',
            new_name='client_note',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_notes',
            new_name='product_note',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_products',
            field=models.ManyToManyField(to='mdpapp.Product'),
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
