# Generated by Django 3.0.6 on 2020-06-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdpapp', '0012_auto_20200531_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_total',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_purchase_price',
            field=models.DecimalField(decimal_places=3, help_text="'0' para ignorar.", max_digits=7, null=True, verbose_name='Preço de Custo'),
        ),
    ]
